Coding.Lizards.Pokemon.Tools.Web/Models/AttackViewModels.cs
namespace Coding.Lizards.Pokemon.Tools.Web.Models {

	using Dapper;
	using System;
	using System.Configuration;
	using System.Data.SqlClient;
	using System.Linq;
	using System.Threading.Tasks;

	public class AddAttackViewModel : BaseAddViewModel<AttackModel, int> {

		public override async Task<int> Save() {
			using (var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)) {
				var affectedRows = await sqlconnection.ExecuteAsync(@"INSERT INTO Attack (
					Id,
					GermanName,
					EnglishName,
					FrenchName,
					Type,
					Strength,
					Accuracy
				) VALUES (
					@id,
					@germanName,
					@englishName,
					@frenchName,
					@type,
					@strength,
					@accuracy
				)", new {
					germanName = Item.GermanName,
					englishName = Item.EnglishName,
					frenchName = Item.FrenchName,
					type = Item.Type,
					strength = Item.Strength,
					accuracy = Item.Accuracy,
					id = Item.Id
				});
				if (affectedRows < 1) {
					throw new Exception("Attack not inserted");
				}
				return Item.Id;
			}
		}
	}

	public class EditAttackViewModel : BaseEditViewModel<AttackModel, int> {

		public override async Task LoadData(int id) {
			using (var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)) {
				var items = await sqlconnection.QueryAsync<AttackModel>("SELECT [Name], [DamageClass], [Type], [AttackPoints], [Priority], [Accuracy], [DirectHitChance] FROM [dbo].[Attack] WHERE NationalDexId = @id", new { id = id });
				this.Item = items.First();
			}
		}

		public override async Task<int> Save() {
			using (var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)) {
				await sqlconnection.ExecuteAsync(@"UPDATE Attack SET
[GermanName] = @germanName,
[EnglishName] = @englishName,
[Frenchname] = @frenchName,
[Type] = @type,
[Strength] = @strength,
[Accuracy] = @accuracy
WHERE NationalDexId = @id", new {
					germanName = Item.GermanName,
					englishName = Item.EnglishName,
					frenchName = Item.FrenchName,
					type = Item.Type,
					strength = Item.Strength,
					accuracy = Item.Accuracy,
					id = Item.Id
				});
				return Item.Id;
			}
		}
	}

	public class DetailsAttackViewModel : BaseDetailsViewModel<AttackModel, int> {

		public override async Task LoadData(int id) {
			using (var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)) {
				var items = await sqlconnection.QueryAsync<AttackModel>("SELECT [Id], [EnglishName], [GermanName], [FrenchName], [DamageClass], [Type], [Accuracy], [Strength] FROM [dbo].[Attack] WHERE Id = @id", new { id = id });
				this.Item = items.First();
			}
		}
	}

	public class DeleteAttackViewModel : BaseDeleteViewModel<AttackModel, int> {

		public override async Task<bool> Delete() {
			try {
				using (var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)) {
					await sqlconnection.ExecuteAsync("DELETE FROM Attack WHERE Id = @id", new { id = Item.Id });
				}
				return true;
			} catch (Exception ex) {
				return false;
			}
		}

		public override async Task LoadData(int id) {
			using (var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)) {
				var items = await sqlconnection.QueryAsync<AttackModel>("SELECT [Id], [EnglishName], [GermanName], [FrenchName], [DamageClass], [Type], [Accuracy], [Strength] FROM [dbo].[Attack] WHERE Id = @id", new { id = id });
				this.Item = items.First();
			}
		}
	}

	public class ListAttackViewModel : BaseListViewModel<AttackModel, int> {

		public override async Task LoadData() {
			using (var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)) {
				this.Items = await sqlconnection.QueryAsync<AttackModel>("SELECT [Id], [EnglishName], [GermanName], [FrenchName], [DamageClass], [Type], [Accuracy], [Strength] FROM [dbo].[Attack]");
			}
		}
	}
}

Coding.Lizards.Pokemon.Tools.Web/Controllers/AttackController.cs
namespace Coding.Lizards.Pokemon.Tools.Web.Controllers {

    using Models;

    public class AttackController : BaseController<AttackModel, int, ListAttackViewModel, AddAttackViewModel, EditAttackViewModel, DetailsAttackViewModel, DeleteAttackViewModel> {
    }
}

Coding.Lizards.Pokemon.Tools.Web/Views/Attack/Add.cshtml
@model AddAttackViewModel
@{
    ViewBag.Title = Texts.Attack_Add_Title;
}

<div class="ui middle aligned center aligned grid">
    <div class="ui twelve wide left aligned column stacked segment">
        <div class="ui secondary pointing menu">
            <div class="header item">@ViewBag.Title</div>
        </div>
        @using (Html.BeginForm("Add", "Attack", FormMethod.Post, new { @class = "ui form", role = "form" })) {
            <div class="four fields">
                <div class="field">
                    <label for="@Html.IdFor(m => m.Item.Id)">#</label>
                    @Html.TextBoxFor(m => m.Item.Id)
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.EnglishName)
                    @Html.TextBoxFor(m => m.Item.EnglishName)
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.GermanName)
                    @Html.TextBoxFor(m => m.Item.GermanName)
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.FrenchName)
                    @Html.TextBoxFor(m => m.Item.FrenchName)
                </div>
            </div>
            <div class="four fields">
                <div class="field">
                    @Html.LabelFor(m => m.Item.Accuracy)
                    @Html.TextBoxFor(m => m.Item.Accuracy)
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.Strength)
                    @Html.TextBoxFor(m => m.Item.Strength)
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.DamageClass)
                    @Html.EnumDropDownListFor(m => m.Item.DamageClass, new { @class = "ui search dropdown" })
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.Type)
                    @Html.EnumDropDownListFor(m => m.Item.Type, new { @class = "ui search dropdown" })
                </div>
            </div>
            <div class="ui right floated buttons">
                <a href="/user" class="ui button">@Texts.Attack_Add_Cancel</a>
                <div class="or" data-text="@Texts.Or"></div>
                <button type="submit" class="ui animated submit primary button">
                    <div class="visible content">@Texts.Attack_Add_Submit</div>
                    <div class="hidden content">
                        <i class="right save icon"></i>
                    </div>
                </button>
            </div>
        }
    </div>
</div>
@section scripts {
    <script>
        $('select').dropdown();
    </script>
}

Coding.Lizards.Pokemon.Tools.Web/Views/Attack/Delete.cshtml
@model DeleteAttackViewModel
@{
    ViewBag.Title = Texts.Attack_Delete_Title;
}

<div class="ui middle aligned center aligned grid">
    @using (Html.BeginForm("Delete", "Attack", FormMethod.Post, new { @class = "ui compact segment" })) {
        @Html.HiddenFor(m => m.Item.Id)
        <div class="ui secondary pointing menu">
            <div class="header item">@ViewBag.Title</div>
        </div>
        <div class="content">
            @string.Format(Texts.Attack_Delete_Content, Model.Item.GetLocalizedName())
        </div>
        <div class="ui right floated buttons">
            <a href="/Attack" class="ui button">@Texts.Attack_Delete_Cancel</a>
            <div class="or" data-text="@Texts.Or"></div>
            <button type="submit" class="ui animated submit primary button">
                <div class="visible content">@Texts.Attack_Delete_Submit</div>
                <div class="hidden content">
                    <i class="right save icon"></i>
                </div>
            </button>
        </div>
    }
</div>

Coding.Lizards.Pokemon.Tools.Web/Views/Attack/Details.cshtml
@model DetailsAttackViewModel
@{
    ViewBag.Title = Texts.Attack_Details_Title;
}

<div class="ui middle aligned center aligned grid">
    <div class="ui twelve wide left aligned column stacked segment">
        <div class="ui secondary pointing menu">
            <div class="header item">@Model.Item.GetLocalizedName() &mdash; @ViewBag.Title</div>
            @if (User.Identity.IsAuthenticated) {
                <div class="right menu">
                    <a href="@Url.Action("Edit", new { id = Model.Item.Id })" class="item"><i class="edit icon"></i> @Texts.Attack_Details_Edit</a>
                    <a href="@Url.Action("Delete", new { id = Model.Item.Id })" class="item"><i class="trash icon"></i> @Texts.Attack_Details_Delete</a>
                </div>
            }
        </div>
        <div class="ui form">
            <div class="four fields">
                <div class="field">
                    <label for="@Html.IdFor(m => m.Item.Id)">#</label>
                    <div class="ui transparent input">
                        @Html.TextBoxFor(m => m.Item.Id, new { @readonly = true })
                    </div>
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.EnglishName)
                    <div class="ui transparent input">
                        @Html.TextBoxFor(m => m.Item.EnglishName, new { @readonly = true })
                    </div>
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.GermanName)
                    <div class="ui transparent input">
                        @Html.TextBoxFor(m => m.Item.GermanName, new { @readonly = true })
                    </div>
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.FrenchName)
                    <div class="ui transparent input">
                        @Html.TextBoxFor(m => m.Item.FrenchName, new { @readonly = true })
                    </div>
                </div>
            </div>
            <div class="four fields">
                <div class="field">
                    @Html.LabelFor(m => m.Item.Accuracy)
                    <div class="ui transparent input">
                        @Html.TextBoxFor(m => m.Item.Accuracy, new { @readonly = true })
                    </div>
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.Strength)
                    <div class="ui transparent input">
                        @Html.TextBoxFor(m => m.Item.Strength, new { @readonly = true })
                    </div>
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.DamageClass)
                    <div class="ui transparent input">
                        <input type="text" value="@Model.Item.DamageClass.DisplayName()" />
                    </div>
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.Type)
                    <div class="ui transparent input">
                        <input type="text" value="@Model.Item.Type.DisplayName()" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Coding.Lizards.Pokemon.Tools.Web/Views/Attack/Edit.cshtml
@model EditAttackViewModel
@{
    ViewBag.Title = Texts.Attack_Edit_Title;
}

<div class="ui middle aligned center aligned grid">
    <div class="ui twelve wide left aligned column stacked segment">
        <div class="ui secondary pointing menu">
            <div class="header item">@ViewBag.Title</div>
        </div>
        @using (Html.BeginForm("Edit", "Attack", FormMethod.Post, new { @class = "ui form", role = "form" })) {
            <div class="four fields">
                <div class="field">
                    <label for="@Html.IdFor(m => m.Item.Id)">#</label>
                    @Html.TextBoxFor(m => m.Item.Id)
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.EnglishName)
                    @Html.TextBoxFor(m => m.Item.EnglishName)
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.GermanName)
                    @Html.TextBoxFor(m => m.Item.GermanName)
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.FrenchName)
                    @Html.TextBoxFor(m => m.Item.FrenchName)
                </div>
            </div>
            <div class="four fields">
                <div class="field">
                    @Html.LabelFor(m => m.Item.Accuracy)
                    @Html.TextBoxFor(m => m.Item.Accuracy)
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.Strength)
                    @Html.TextBoxFor(m => m.Item.Strength)
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.DamageClass)
                    @Html.EnumDropDownListFor(m => m.Item.DamageClass, new { @class = "ui search dropdown" })
                </div>
                <div class="field">
                    @Html.LabelFor(m => m.Item.Type)
                    @Html.EnumDropDownListFor(m => m.Item.Type, new { @class = "ui search dropdown" })
                </div>
            </div>
            <div class="ui right floated buttons">
                <a href="/user" class="ui button">@Texts.Attack_Edit_Cancel</a>
                <div class="or" data-text="@Texts.Or"></div>
                <button type="submit" class="ui animated submit primary button">
                    <div class="visible content">@Texts.Attack_Edit_Submit</div>
                    <div class="hidden content">
                        <i class="right save icon"></i>
                    </div>
                </button>
            </div>
        }
    </div>
</div>
@section scripts {
    <script>
        $('select').dropdown();
        $('[data-action=openfile]').click(function () {
            var $this = $(this);
            var $target = $($this.data('target'));
            var $textbox = $($this.data('textbox'));
            $target.click();
            $textbox.val($target.val());
        });
    </script>
}

Coding.Lizards.Pokemon.Tools.Web/Views/Attack/Index.cshtml
@model ListAttackViewModel
@{
    ViewBag.Title = Texts.Attack_List_Title;
}

<div class="ui stacked segment">
    <div class="ui secondary pointing menu">
        <div class="header item">@ViewBag.Title</div>
        @if (User.Identity.IsAuthenticated) {
            <a class="right item" href="@Url.Action("Add")"><i class="add icon"></i> @Texts.User_List_Add</a>
        }
    </div>
    <table class="ui compact striped table">
        <thead>
            <tr>
                <th>#</th>
                <th>@Texts.Attack_List_Name</th>
                <th>@Texts.Attack_List_Type</th>
                <th>@Texts.Attack_List_Accuracy</th>
                <th>@Texts.Attack_List_Strength</th>
                <th>@Texts.Attack_List_DamageClass</th>
                <th>@Texts.Attack_List_Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>@item.Id</td>
                    <td>
                        @Html.ActionLink(item.GetLocalizedName(), "Details", new { id = item.Id })
                    </td>
                    <td>@item.Type.DisplayName()</td>
                    <td>@item.Accuracy</td>
                    <td>@item.Strength</td>
                    <td>@item.DamageClass</td>
                    <td>
                        <div class="ui buttons">
                            <a href="@Url.Action("Edit", new { id = item.Id })" class="ui tiny button"><i class="edit icon"></i> @Texts.Attack_List_Edit</a>
                            <a href="@Url.Action("Delete", new { id = item.Id })" class="ui tiny red button"><i class="trash icon"></i> @Texts.Attack_List_Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>