Coding.Lizards.Pokemon.Tools.Web/Controllers/HomeController.cs
namespace Coding.Lizards.Pokemon.Tools.Web.Controllers {

    using Models;
    using Dapper;
    using System.Configuration;
    using System.Data.SqlClient;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    public class HomeController : Controller {

        public async Task<ActionResult> Index() {
            var vm = new HomePageViewModel();
            await vm.LoadData();
            return View(vm);
        }

        public async Task<ActionResult> Attack(int id) {
            var attack = new DetailsAttackViewModel();
            await attack.LoadData(id);
            return Json(attack.Item, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Pokemon(int id) {
            var pokemon = new DetailsPokemonViewModel();
            await pokemon.LoadData(id);
            return Json(pokemon.Item, JsonRequestBehavior.AllowGet);
        }

        public async Task<float> Effect(int usedattack, int defendingpokemon) {
            var attack = new DetailsAttackViewModel();
            await attack.LoadData(usedattack);

            var pokemon = new DetailsPokemonViewModel();
            await pokemon.LoadData(defendingpokemon);

            using (var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)) {
                var effect = await sqlconnection.ExecuteScalarAsync<float>("SELECT Effect FROM TypeEffect WHERE AttackingType = @attack AND DefendingType = @defending", new { attack = attack.Item.Type, defending = pokemon.Item.FirstType });
                if (pokemon.Item.SecondType.HasValue) {
                    effect *= await sqlconnection.ExecuteScalarAsync<float>("SELECT Effect FROM TypeEffect WHERE AttackingType = @attack AND DefendingType = @defending", new { attack = attack.Item.Type, defending = pokemon.Item.SecondType });
                }
                return effect;
            }
        }
    }
}

Coding.Lizards.Pokemon.Tools.Web/Controllers/PokemonController.cs
namespace Coding.Lizards.Pokemon.Tools.Web.Controllers {

    using Dapper;
    using Models;
    using System.Configuration;
    using System.Data.SqlClient;
    using System.Drawing;
    using System.Drawing.Imaging;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    public class PokemonController : BaseController<PokemonModel, int, ListPokemonViewModel, AddPokemonViewModel, EditPokemonViewModel, DetailsPokemonViewModel, DeletePokemonViewModel> {

        public async Task<ActionResult> GetThumbnail(int id) {
            using (var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)) {
                var data = await sqlconnection.ExecuteScalarAsync<byte[]>("SELECT Thumbnail FROM Pokemon WHERE NationalDexId = @id", new { id = id });
                return File(data, "image/gif");
            }
        }

        public async Task<ActionResult> GetSprite(int id) {
            using (var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)) {
                var data = await sqlconnection.ExecuteScalarAsync<byte[]>("SELECT Sprite FROM Pokemon WHERE NationalDexId = @id", new { id = id });
                return File(data, "image/gif");
            }
        }

        public override async Task<ActionResult> Add(AddPokemonViewModel model) {
            var thumbnail = Image.FromStream(Request.Files["Thumbnail"].InputStream);
            using (var ms = new MemoryStream()) {
                thumbnail.Save(ms, ImageFormat.Gif);
                ms.Position = 0;
                model.Item.Thumbnail = ms.ToArray();
            }

            var sprite = Image.FromStream(Request.Files["Sprite"].InputStream);
            using (var ms = new MemoryStream()) {
                sprite.Save(ms, ImageFormat.Gif);
                ms.Position = 0;
                model.Item.Sprite = ms.ToArray();
            }

            return await base.Add(model);
        }

        public override async Task<ActionResult> Edit(EditPokemonViewModel model) {
            if (Request.Files.Get("Thumbnail").ContentLength > 0) {
                var thumbnail = Image.FromStream(Request.Files["Thumbnail"].InputStream);
                using (var ms = new MemoryStream()) {
                    thumbnail.Save(ms, ImageFormat.Gif);
                    ms.Position = 0;
                    model.Item.Thumbnail = ms.ToArray();
                }
            }

            if (Request.Files.Get("Sprite").ContentLength > 0) {
                var sprite = Image.FromStream(Request.Files["Sprite"].InputStream);
                using (var ms = new MemoryStream()) {
                    sprite.Save(ms, ImageFormat.Gif);
                    ms.Position = 0;
                    model.Item.Sprite = ms.ToArray();
                }
            }

            return await base.Edit(model);
        }
    }
}

Coding.Lizards.Pokemon.Tools.Web/Views/Home/Index.cshtml
@model HomePageViewModel
@{
    ViewBag.Title = Texts.Home_Index_Title;
}
<div class="ui middle aligned center aligned grid">
    <div class="ui twelve wide left aligned column stacked segment">
        <div class="ui secondary pointing menu">
            <div class="header item">@ViewBag.Title</div>
            <div class="right menu">
                <a data-tab="fighting" class="active item">@Texts.Home_Index_Fight</a>
                <a data-tab="xpcalc" class="item">@Texts.Home_Index_XpCalc</a>
            </div>
        </div>
        <div data-tab="fighting" class="ui active basic tab segment">
            <div class="ui grid form">
                <div class="ui eight wide column">
                    <h4 class="ui dividing header">@Texts.Home_Index_MyPokemon</h4>
                    <div class="inline field">
                        <label>@Texts.Home_Index_Level</label>
                        @Html.DropDownList("fight_attackingpokemon_level", new SelectList(Enumerable.Range(1, 100)), new { @class = "ui compact search dropdown" })
                        <label>@Texts.Home_Index_Pokemon</label>
                        <div id="attackingpokemon" class="ui search selection dropdown">
                            <div class="default text">@Texts.Home_Index_SearchPokemon</div>
                            <i class="dropdown icon"></i>
                            <div class="menu">
                                @foreach (var item in Model.Pokemon) {
                                    <div data-value="@item.Id" class="item">
                                        <img src="@Url.Action("GetThumbnail", "Pokemon", new { id = item.Id })" alt="" />
                                        @item.GetLocalizedName()
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ui eight wide column">
                    <h4 class="ui dividing header">@Texts.Home_Index_OpponentPokemon</h4>
                    <div class="inline field">
                        <label>@Texts.Home_Index_Level</label>
                        @Html.DropDownList("fight_defendingpokemon_level", new SelectList(Enumerable.Range(1, 100)), new { @class = "ui compact search dropdown" })
                        <label>@Texts.Home_Index_Pokemon</label>
                        <div id="defendingpokemon" class="ui search selection dropdown">
                            <div class="default text">@Texts.Home_Index_SearchPokemon</div>
                            <i class="dropdown icon"></i>
                            <div class="menu">
                                @foreach (var item in Model.Pokemon) {
                                    <div data-value="@item.Id" class="item">
                                        <img src="@Url.Action("GetThumbnail", "Pokemon", new { id = item.Id })" alt="" />
                                        @item.GetLocalizedName()
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <label>@Texts.Home_Index_MinDamage</label>
                        <div class="ui transparent input">
                            <input readonly type="text" id="mindamage" />
                        </div>
                        <label>@Texts.Home_Index_MaxDamage</label>
                        <div class="ui transparent input">
                            <input readonly type="text" id="maxdamage" />
                        </div>
                    </div>
                </div>
                <div class="ui sixteen wide column">
                    <h4 class="ui dividing header">@Texts.Home_Index_UsedAttack</h4>
                    <div id="usedattack" class="ui fluid search selection dropdown">
                        <div class="default text">@Texts.Home_Index_SearchAttack</div>
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            @foreach (var item in Model.Attacks) {
                                <div data-value="@item.Id" class="item">
                                    @item.GetLocalizedName()
                                    (@item.Type.DisplayName() &mdash; @Texts.Attack_List_Strength: @item.Strength)
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <div class="ui right aligned sixteen wide column">
                    <button data-action="calcattack" class="ui primary button" type="button">@Texts.Home_Index_Fight</button>
                </div>
            </div>
        </div>
        <div data-tab="xpcalc" class="ui basic tab segment">XP Calc</div>
    </div>
</div>

@section scripts {
    <script>
        $(function () {
            $('.menu .item').tab();
            $('select, .ui.dropdown').dropdown();

            var recalculateAttack = function () {
                var calculateHp = function (base, dv, fp, level) {
                    return Math.floor((2 * base + dv + (fp / 4) + 100) * (level / 100) + 10);
                };
                var calculateOther = function (base, dv, fp, level) {
                    return Math.floor(((2 * base + dv + (fp / 4)) * (level / 100) + 5) * 1);
                };

                var attackingPokemon = undefined;
                var defendingPokemon = undefined;
                var usedAttack = undefined;
                $.getJSON('/home/attack?id=' + $('#usedattack').dropdown('get value')).then(function (attack) {
                    usedAttack = attack;
                    return $.getJSON('/home/pokemon?id=' + $('#attackingpokemon').dropdown('get value'));
                }).then(function (pokemon) {
                    attackingPokemon = pokemon;
                    return $.getJSON('/home/pokemon?id=' + $('#defendingpokemon').dropdown('get value'));
                }).then(function (pokemon) {
                    defendingPokemon = pokemon;
                    return $.get('/home/effect?usedattack=' + usedAttack.Id + '&defendingpokemon=' + defendingPokemon.Id);
                }).then(function (effect) {
                    var calcDamage = function (z, dv, fp) {
                        var baseStrength = usedAttack.Strength;
                        var basedamage = baseStrength;
                        var attackingLevel = $('#fight_attackingpokemon_level').val();
                        var defendingLevel = $('#fight_defendingpokemon_level').val();

                        var attack = 0;
                        var defense = 0;
                        if (usedAttack.DamageClass == 0) {
                            attack = calculateOther(attackingPokemon.BaseAttack, dv, fp, attackingLevel);
                            defense = calculateOther(defendingPokemon.BaseDefense, dv, fp, defendingLevel);
                        } else if (usedAttack.DamageClass == 1) {
                            attack = calculateOther(attackingPokemon.BaseSpecialAttack, dv, fp, attackingLevel);
                            defense = calculateOther(defendingPokemon.BaseSpecialDefense, dv, fp, defendingLevel);
                        } else {
                            return 0;
                        }

                        var directhit = 1;

                        var f1 = 1;
                        var f2 = 1;
                        var f3 = 1;

                        var stab = 1;
                        if (usedAttack.Type == attackingPokemon.FirstType || usedAttack.Type == attackingPokemon.SecondType) {
                            stab = 1.5;
                        }

                        return ((attackingLevel * (2 / 5) + 2) * basedamage * (attack / (50 * defense)) * f1 + 2) * directhit * f2 * (z / 100) * stab * effect * f3;
                    };
                    var minDamage = Math.floor(calcDamage(85, 1, 1));
                    var maxDamage = Math.floor(calcDamage(100, 31, 252));
                    $('#mindamage').val(minDamage);
                    $('#maxdamage').val(maxDamage);
                });
            };
            $('[data-action=calcattack]').click(function () {
                recalculateAttack();
            });
        });
    </script>
}